version: '3'

services:
  mqtt:
    image: eclipse-mosquitto 
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto-docker:/mosquitto

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - /home/buri/coding/SSV/grafana/grafana-plugin:/var/lib/grafana/plugins

volumes:
  grafana-storage:

  # telegraf:
  # prometheus:
  # influxDB:
